### ISSUE TITLE
Separate `gptifier.toml` into command specific sections

### ISSUE THREAD

**Issue by dsw7** [dsw7/GPTifier#59]
## Impetus
Right now we have a basic `profile` section:
```toml
# ...

[profile]
# Specify a default model to use such as "gpt-3.5-turbo" or "gpt-4"
model = "gpt-3.5-turbo"

# ...
```
But since merging a fix for https://github.com/dsw7/GPTifier/issues/57, we need to add additional default models, such as a default model for the new `embed` command.
